spring.application.name=Cadastro e login


spring.datasource.username=root
spring.datasource.password=235689
spring.datasource.url=jdbc:mysql://localhost:3306/SpringWeb?useTimezone=true&serverTimezone=UTC

spring.jpa.show_sql=true
spring.jpa.hibernate.ddl-auto=update